In [3]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Dados_Tratados.csv')

In [4]:
qualy = df.select_dtypes(exclude=[np.number])
quanty = df.select_dtypes(exclude=[object])

In [8]:
for i in range(len(qualy.columns)):
    for j in range(i+1, len(qualy.columns)):
        tab_qualy = pd.crosstab(index=qualy[qualy.columns[i]], columns=qualy[qualy.columns[j]], normalize='index').applymap('{:.2%}'.format).T
        display(tab_qualy)
        print('\n' + '-'*30 + '\n')

Gênero          Feminino Masculino
Idade
18-24 anos        44.05%    46.97%
25-34 anos        38.10%    34.85%
35-44 anos        15.48%    15.15%
45 anos ou mais    2.38%     3.03%

------------------------------

Gênero             Feminino Masculino
Escolaridade
Ensino Fundamental    0.00%     1.52%
Ensino Médio         40.48%    36.36%
Ensino Superior      48.81%    48.48%
Pós-Graduação        10.71%    13.64%

------------------------------

Gênero        Feminino Masculino
Estado Civil
Casado(a)       30.95%    13.64%
Divorciado(a)    1.19%     1.52%
Outros           1.19%     4.55%
Solteiro(a)     65.48%    80.30%
Viúvo(a)         1.19%     0.00%

------------------------------

Gênero                            Feminino Masculino
Renda
Acima de R$ 1.212 até R$ 3.636,00   41.67%    60.61%
Acima de R$ 3.636,00 até R$ 6.000   10.71%    12.12%
Acima de R$ 6.000                    2.38%     3.03%
Até R$ 1.212,00                     45.24%    24.24%

------------------------------

Gênero             Feminino Masculino
Primeira Compra
Ainda não comprei     9.52%     6.06%
Antes da pandemia    52.38%    53.03%
Depois da pandemia   13.10%    12.12%
Durante a pandemia   25.00%    28.79%

------------------------------

Gênero                                             Feminino Masculino
Formato do Infoproduto
Texto: PDF e E-book                                  30.95%    31.82%
Visual: Infográficos, figuras, página de vendas...    5.95%     4.55%
Vídeo: Vídeo aulas, mentorias, screencasts , cu...   60.71%    60.61%
Áudio: Áudiobook e podcast                            2.38%     3.03%

------------------------------

Gênero                  Feminino Masculino
Área mais Consumida
Desenvolvimento Pessoal   19.05%    30.30%
Educação                  60.71%    53.03%
Finanças                   7.14%     7.58%
Saúde                     13.10%     9.09%

------------------------------

Gênero                      Feminino Masculino
Disposição Financeira
Acima de R$ 200,00            21.43%    31.82%
Entre R$ 100,00 e R$ 200,00   23.81%    21.21%
Entre R$ 50,00 e R$ 100,00.   42.86%    34.85%
Menos de R$ 50,00             11.90%    12.12%

------------------------------

Gênero                                             Feminino Masculino
Influência na Compra
Avaliações e depoimentos de clientes                 22.62%    21.21%
Conteúdo do infoproduto (tema/relevância)            28.57%    22.73%
Conteúdo gratuito oferecido pelo produtor             7.14%    12.12%
Garantia de devolução do dinheiro                     2.38%     0.00%
Preço                                                10.71%     6.06%
Qualidade da apresentação (vídeo, áudio, design...   16.67%    13.64%
Recomendações de amigos/familiares                   11.90%    24.24%

------------------------------

Gênero                                             Feminino Masculino
Primeiro Contato
Pesquisa em mecanismos de busca, como o Google       19.05%    21.21%
Por meio das redes sociais, como Instagram, Tik...   41.67%    34.85%
Por meio de anúncios online, como no Facebook o...    7.14%    12.12%
Recomendação de amigos ou colegas                    32.14%    31.82%

------------------------------

Gênero                                             Feminino Masculino
Motivação para Compra
Aquisição de conhecimento específico                 28.57%    30.30%
Desenvolvimento de habilidades técnicas               7.14%    13.64%
Empreendedorismo ou criação de negócio próprio        1.19%     0.00%
Facilidade de aprendizado online                      7.14%     7.58%
Flexibilidade de horário de estudo                   13.10%     6.06%
Ganhos financeiros                                    7.14%     4.55%
Indicação de colegas ou amigos                        1.19%     4.55%
Mudar de Carreira (aprender uma nova profissão)       5.95%    10.61%
Preparação para exames, concursos ou certificações   15.48%    18.18%
Realização de objetivos de vida                      10.71%     3.03%
Solução para um problema específico                   2.38%     1.52%

------------------------------

Idade              18-24 anos 25-34 anos 35-44 anos 45 anos ou mais
Escolaridade
Ensino Fundamental      0.00%      0.00%      0.00%          25.00%
Ensino Médio           51.47%     23.64%     34.78%          50.00%
Ensino Superior        48.53%     54.55%     39.13%          25.00%
Pós-Graduação           0.00%     21.82%     26.09%           0.00%

------------------------------

Idade         18-24 anos 25-34 anos 35-44 anos 45 anos ou mais
Estado Civil
Casado(a)          7.35%     30.91%     43.48%          75.00%
Divorciado(a)      0.00%      0.00%      8.70%           0.00%
Outros             0.00%      5.45%      4.35%           0.00%
Solteiro(a)       92.65%     63.64%     39.13%          25.00%
Viúvo(a)           0.00%      0.00%      4.35%           0.00%

------------------------------

Idade,18-24 anos,25-34 anos,35-44 anos,45 anos ou mais
Renda,,,,
"Acima de R$ 1.212 até R$ 3.636,00",51.47%,54.55%,34.78%,50.00%
"Acima de R$ 3.636,00 até R$ 6.000",1.47%,21.82%,13.04%,25.00%
Acima de R$ 6.000,0.00%,3.64%,8.70%,0.00%
"Até R$ 1.212,00",47.06%,20.00%,43.48%,25.00%

------------------------------

Idade              18-24 anos 25-34 anos 35-44 anos 45 anos ou mais
Primeira Compra
Ainda não comprei      13.24%      3.64%      0.00%          25.00%
Antes da pandemia      36.76%     60.00%     78.26%          75.00%
Depois da pandemia     16.18%     10.91%      8.70%           0.00%
Durante a pandemia     33.82%     25.45%     13.04%           0.00%

------------------------------

Idade,18-24 anos,25-34 anos,35-44 anos,45 anos ou mais
Formato do Infoproduto,,,,
Texto: PDF e E-book,32.35%,34.55%,26.09%,0.00%
"Visual: Infográficos, figuras, página de vendas, site, Template e planilha",5.88%,5.45%,4.35%,0.00%
"Vídeo: Vídeo aulas, mentorias, screencasts , cursos e lives, Videocast , filmes ou documentários",58.82%,60.00%,60.87%,100.00%
Áudio: Áudiobook e podcast,2.94%,0.00%,8.70%,0.00%

------------------------------

Idade                   18-24 anos 25-34 anos 35-44 anos 45 anos ou mais
Área mais Consumida
Desenvolvimento Pessoal     26.47%     21.82%     17.39%          50.00%
Educação                    54.41%     58.18%     65.22%          50.00%
Finanças                     8.82%      5.45%      8.70%           0.00%
Saúde                       10.29%     14.55%      8.70%           0.00%

------------------------------

Idade                       18-24 anos 25-34 anos 35-44 anos 45 anos ou mais
Disposição Financeira
Acima de R$ 200,00              22.06%     29.09%     34.78%           0.00%
Entre R$ 100,00 e R$ 200,00     19.12%     29.09%     21.74%           0.00%
Entre R$ 50,00 e R$ 100,00.     44.12%     36.36%     30.43%          50.00%
Menos de R$ 50,00               14.71%      5.45%     13.04%          50.00%

------------------------------

Idade,18-24 anos,25-34 anos,35-44 anos,45 anos ou mais
Influência na Compra,,,,
Avaliações e depoimentos de clientes,30.88%,16.36%,13.04%,0.00%
Conteúdo do infoproduto (tema/relevância),23.53%,27.27%,34.78%,0.00%
Conteúdo gratuito oferecido pelo produtor,7.35%,10.91%,13.04%,0.00%
Garantia de devolução do dinheiro,0.00%,1.82%,4.35%,0.00%
Preço,10.29%,7.27%,8.70%,0.00%
"Qualidade da apresentação (vídeo, áudio, design, etc.)",11.76%,14.55%,21.74%,50.00%
Recomendações de amigos/familiares,16.18%,21.82%,4.35%,50.00%

------------------------------

Idade,18-24 anos,25-34 anos,35-44 anos,45 anos ou mais
Primeiro Contato,,,,
"Pesquisa em mecanismos de busca, como o Google",16.18%,25.45%,21.74%,0.00%
"Por meio das redes sociais, como Instagram, TikTok, YouTube ou Twitter",39.71%,36.36%,47.83%,0.00%
"Por meio de anúncios online, como no Facebook ou Google Ads",7.35%,10.91%,8.70%,25.00%
Recomendação de amigos ou colegas,36.76%,27.27%,21.74%,75.00%

------------------------------

Idade,18-24 anos,25-34 anos,35-44 anos,45 anos ou mais
Motivação para Compra,,,,
Aquisição de conhecimento específico,30.88%,25.45%,30.43%,50.00%
Desenvolvimento de habilidades técnicas,11.76%,9.09%,8.70%,0.00%
Empreendedorismo ou criação de negócio próprio,1.47%,0.00%,0.00%,0.00%
Facilidade de aprendizado online,7.35%,9.09%,4.35%,0.00%
Flexibilidade de horário de estudo,10.29%,10.91%,8.70%,0.00%
Ganhos financeiros,4.41%,3.64%,13.04%,25.00%
Indicação de colegas ou amigos,4.41%,1.82%,0.00%,0.00%
Mudar de Carreira (aprender uma nova profissão),7.35%,10.91%,0.00%,25.00%
"Preparação para exames, concursos ou certificações",13.24%,18.18%,26.09%,0.00%
Realização de objetivos de vida,5.88%,10.91%,4.35%,0.00%
Solução para um problema específico,2.94%,0.00%,4.35%,0.00%

------------------------------

Escolaridade  Ensino Fundamental Ensino Médio Ensino Superior Pós-Graduação
Estado Civil
Casado(a)                100.00%       15.52%          24.66%        38.89%
Divorciado(a)              0.00%        3.45%           0.00%         0.00%
Outros                     0.00%        0.00%           1.37%        16.67%
Solteiro(a)                0.00%       79.31%          73.97%        44.44%
Viúvo(a)                   0.00%        1.72%           0.00%         0.00%

------------------------------

Escolaridade,Ensino Fundamental,Ensino Médio,Ensino Superior,Pós-Graduação
Renda,,,,
"Acima de R$ 1.212 até R$ 3.636,00",100.00%,46.55%,53.42%,44.44%
"Acima de R$ 3.636,00 até R$ 6.000",0.00%,3.45%,10.96%,38.89%
Acima de R$ 6.000,0.00%,0.00%,4.11%,5.56%
"Até R$ 1.212,00",0.00%,50.00%,31.51%,11.11%

------------------------------

Escolaridade,Ensino Fundamental,Ensino Médio,Ensino Superior,Pós-Graduação
Primeira Compra,,,,
Ainda não comprei,0.00%,12.07%,6.85%,0.00%
Antes da pandemia,100.00%,43.10%,50.68%,88.89%
Depois da pandemia,0.00%,15.52%,12.33%,5.56%
Durante a pandemia,0.00%,29.31%,30.14%,5.56%

------------------------------

Escolaridade,Ensino Fundamental,Ensino Médio,Ensino Superior,Pós-Graduação
Formato do Infoproduto,,,,
Texto: PDF e E-book,0.00%,29.31%,32.88%,33.33%
"Visual: Infográficos, figuras, página de vendas, site, Template e planilha",0.00%,6.90%,5.48%,0.00%
"Vídeo: Vídeo aulas, mentorias, screencasts , cursos e lives, Videocast , filmes ou documentários",100.00%,60.34%,58.90%,66.67%
Áudio: Áudiobook e podcast,0.00%,3.45%,2.74%,0.00%

------------------------------

Escolaridade,Ensino Fundamental,Ensino Médio,Ensino Superior,Pós-Graduação
Área mais Consumida,,,,
Desenvolvimento Pessoal,100.00%,29.31%,21.92%,11.11%
Educação,0.00%,51.72%,57.53%,77.78%
Finanças,0.00%,5.17%,9.59%,5.56%
Saúde,0.00%,13.79%,10.96%,5.56%

------------------------------

Escolaridade,Ensino Fundamental,Ensino Médio,Ensino Superior,Pós-Graduação
Disposição Financeira,,,,
"Acima de R$ 200,00",0.00%,18.97%,23.29%,61.11%
"Entre R$ 100,00 e R$ 200,00",0.00%,13.79%,27.40%,33.33%
"Entre R$ 50,00 e R$ 100,00.",0.00%,51.72%,38.36%,5.56%
"Menos de R$ 50,00",100.00%,15.52%,10.96%,0.00%

------------------------------

Escolaridade,Ensino Fundamental,Ensino Médio,Ensino Superior,Pós-Graduação
Influência na Compra,,,,
Avaliações e depoimentos de clientes,0.00%,20.69%,21.92%,27.78%
Conteúdo do infoproduto (tema/relevância),0.00%,24.14%,27.40%,27.78%
Conteúdo gratuito oferecido pelo produtor,0.00%,6.90%,10.96%,11.11%
Garantia de devolução do dinheiro,0.00%,1.72%,1.37%,0.00%
Preço,0.00%,10.34%,9.59%,0.00%
"Qualidade da apresentação (vídeo, áudio, design, etc.)",0.00%,13.79%,15.07%,22.22%
Recomendações de amigos/familiares,100.00%,22.41%,13.70%,11.11%

------------------------------

Escolaridade,Ensino Fundamental,Ensino Médio,Ensino Superior,Pós-Graduação
Primeiro Contato,,,,
"Pesquisa em mecanismos de busca, como o Google",0.00%,17.24%,23.29%,16.67%
"Por meio das redes sociais, como Instagram, TikTok, YouTube ou Twitter",0.00%,37.93%,38.36%,44.44%
"Por meio de anúncios online, como no Facebook ou Google Ads",100.00%,10.34%,8.22%,5.56%
Recomendação de amigos ou colegas,0.00%,34.48%,30.14%,33.33%

------------------------------

Escolaridade,Ensino Fundamental,Ensino Médio,Ensino Superior,Pós-Graduação
Motivação para Compra,,,,
Aquisição de conhecimento específico,0.00%,24.14%,35.62%,22.22%
Desenvolvimento de habilidades técnicas,0.00%,8.62%,9.59%,16.67%
Empreendedorismo ou criação de negócio próprio,0.00%,0.00%,1.37%,0.00%
Facilidade de aprendizado online,0.00%,3.45%,10.96%,5.56%
Flexibilidade de horário de estudo,0.00%,12.07%,6.85%,16.67%
Ganhos financeiros,0.00%,15.52%,0.00%,0.00%
Indicação de colegas ou amigos,0.00%,3.45%,2.74%,0.00%
Mudar de Carreira (aprender uma nova profissão),100.00%,5.17%,10.96%,0.00%
"Preparação para exames, concursos ou certificações",0.00%,13.79%,15.07%,33.33%
Realização de objetivos de vida,0.00%,10.34%,5.48%,5.56%
Solução para um problema específico,0.00%,3.45%,1.37%,0.00%

------------------------------

Estado Civil,Casado(a),Divorciado(a),Outros,Solteiro(a),Viúvo(a)
Renda,,,,,
"Acima de R$ 1.212 até R$ 3.636,00",51.43%,0.00%,75.00%,50.00%,0.00%
"Acima de R$ 3.636,00 até R$ 6.000",22.86%,0.00%,25.00%,7.41%,0.00%
Acima de R$ 6.000,2.86%,0.00%,0.00%,2.78%,0.00%
"Até R$ 1.212,00",22.86%,100.00%,0.00%,39.81%,100.00%

------------------------------

Estado Civil       Casado(a) Divorciado(a)  Outros Solteiro(a) Viúvo(a)
Primeira Compra
Ainda não comprei      2.86%         0.00%   0.00%      10.19%    0.00%
Antes da pandemia     57.14%        50.00%  75.00%      50.00%  100.00%
Depois da pandemia     8.57%        50.00%  25.00%      12.96%    0.00%
Durante a pandemia    31.43%         0.00%   0.00%      26.85%    0.00%

------------------------------

Estado Civil,Casado(a),Divorciado(a),Outros,Solteiro(a),Viúvo(a)
Formato do Infoproduto,,,,,
Texto: PDF e E-book,28.57%,0.00%,25.00%,33.33%,0.00%
"Visual: Infográficos, figuras, página de vendas, site, Template e planilha",5.71%,0.00%,0.00%,5.56%,0.00%
"Vídeo: Vídeo aulas, mentorias, screencasts , cursos e lives, Videocast , filmes ou documentários",65.71%,100.00%,75.00%,58.33%,0.00%
Áudio: Áudiobook e podcast,0.00%,0.00%,0.00%,2.78%,100.00%

------------------------------

Estado Civil            Casado(a) Divorciado(a)  Outros Solteiro(a) Viúvo(a)
Área mais Consumida
Desenvolvimento Pessoal    28.57%        50.00%  25.00%      22.22%    0.00%
Educação                   45.71%         0.00%  75.00%      61.11%  100.00%
Finanças                   11.43%         0.00%   0.00%       6.48%    0.00%
Saúde                      14.29%        50.00%   0.00%      10.19%    0.00%

------------------------------

Estado Civil,Casado(a),Divorciado(a),Outros,Solteiro(a),Viúvo(a)
Disposição Financeira,,,,,
"Acima de R$ 200,00",25.71%,0.00%,50.00%,25.93%,0.00%
"Entre R$ 100,00 e R$ 200,00",28.57%,0.00%,50.00%,19.44%,100.00%
"Entre R$ 50,00 e R$ 100,00.",37.14%,50.00%,0.00%,41.67%,0.00%
"Menos de R$ 50,00",8.57%,50.00%,0.00%,12.96%,0.00%

------------------------------

Estado Civil,Casado(a),Divorciado(a),Outros,Solteiro(a),Viúvo(a)
Influência na Compra,,,,,
Avaliações e depoimentos de clientes,20.00%,0.00%,25.00%,23.15%,0.00%
Conteúdo do infoproduto (tema/relevância),25.71%,0.00%,50.00%,25.93%,0.00%
Conteúdo gratuito oferecido pelo produtor,8.57%,0.00%,0.00%,10.19%,0.00%
Garantia de devolução do dinheiro,5.71%,0.00%,0.00%,0.00%,0.00%
Preço,5.71%,100.00%,0.00%,8.33%,0.00%
"Qualidade da apresentação (vídeo, áudio, design, etc.)",17.14%,0.00%,0.00%,14.81%,100.00%
Recomendações de amigos/familiares,17.14%,0.00%,25.00%,17.59%,0.00%

------------------------------

Estado Civil,Casado(a),Divorciado(a),Outros,Solteiro(a),Viúvo(a)
Primeiro Contato,,,,,
"Pesquisa em mecanismos de busca, como o Google",17.14%,0.00%,50.00%,20.37%,0.00%
"Por meio das redes sociais, como Instagram, TikTok, YouTube ou Twitter",48.57%,100.00%,25.00%,34.26%,100.00%
"Por meio de anúncios online, como no Facebook ou Google Ads",14.29%,0.00%,0.00%,8.33%,0.00%
Recomendação de amigos ou colegas,20.00%,0.00%,25.00%,37.04%,0.00%

------------------------------

Estado Civil,Casado(a),Divorciado(a),Outros,Solteiro(a),Viúvo(a)
Motivação para Compra,,,,,
Aquisição de conhecimento específico,31.43%,0.00%,50.00%,28.70%,0.00%
Desenvolvimento de habilidades técnicas,8.57%,0.00%,25.00%,10.19%,0.00%
Empreendedorismo ou criação de negócio próprio,0.00%,0.00%,0.00%,0.93%,0.00%
Facilidade de aprendizado online,2.86%,0.00%,0.00%,9.26%,0.00%
Flexibilidade de horário de estudo,5.71%,50.00%,25.00%,10.19%,0.00%
Ganhos financeiros,8.57%,50.00%,0.00%,3.70%,100.00%
Indicação de colegas ou amigos,0.00%,0.00%,0.00%,3.70%,0.00%
Mudar de Carreira (aprender uma nova profissão),8.57%,0.00%,0.00%,8.33%,0.00%
"Preparação para exames, concursos ou certificações",22.86%,0.00%,0.00%,15.74%,0.00%
Realização de objetivos de vida,11.43%,0.00%,0.00%,6.48%,0.00%
Solução para um problema específico,0.00%,0.00%,0.00%,2.78%,0.00%

------------------------------

Renda,"Acima de R$ 1.212 até R$ 3.636,00","Acima de R$ 3.636,00 até R$ 6.000",Acima de R$ 6.000,"Até R$ 1.212,00"
Primeira Compra,,,,
Ainda não comprei,4.00%,5.88%,0.00%,14.81%
Antes da pandemia,53.33%,70.59%,100.00%,42.59%
Depois da pandemia,14.67%,5.88%,0.00%,12.96%
Durante a pandemia,28.00%,17.65%,0.00%,29.63%

------------------------------

Renda,"Acima de R$ 1.212 até R$ 3.636,00","Acima de R$ 3.636,00 até R$ 6.000",Acima de R$ 6.000,"Até R$ 1.212,00"
Formato do Infoproduto,,,,
Texto: PDF e E-book,37.33%,17.65%,75.00%,24.07%
"Visual: Infográficos, figuras, página de vendas, site, Template e planilha",5.33%,0.00%,0.00%,7.41%
"Vídeo: Vídeo aulas, mentorias, screencasts , cursos e lives, Videocast , filmes ou documentários",56.00%,82.35%,25.00%,62.96%
Áudio: Áudiobook e podcast,1.33%,0.00%,0.00%,5.56%

------------------------------

Renda,"Acima de R$ 1.212 até R$ 3.636,00","Acima de R$ 3.636,00 até R$ 6.000",Acima de R$ 6.000,"Até R$ 1.212,00"
Área mais Consumida,,,,
Desenvolvimento Pessoal,25.33%,23.53%,0.00%,24.07%
Educação,56.00%,58.82%,100.00%,55.56%
Finanças,8.00%,17.65%,0.00%,3.70%
Saúde,10.67%,0.00%,0.00%,16.67%

------------------------------

Renda,"Acima de R$ 1.212 até R$ 3.636,00","Acima de R$ 3.636,00 até R$ 6.000",Acima de R$ 6.000,"Até R$ 1.212,00"
Disposição Financeira,,,,
"Acima de R$ 200,00",28.00%,47.06%,25.00%,16.67%
"Entre R$ 100,00 e R$ 200,00",24.00%,35.29%,0.00%,18.52%
"Entre R$ 50,00 e R$ 100,00.",38.67%,17.65%,50.00%,46.30%
"Menos de R$ 50,00",9.33%,0.00%,25.00%,18.52%

------------------------------

Renda,"Acima de R$ 1.212 até R$ 3.636,00","Acima de R$ 3.636,00 até R$ 6.000",Acima de R$ 6.000,"Até R$ 1.212,00"
Influência na Compra,,,,
Avaliações e depoimentos de clientes,24.00%,5.88%,0.00%,25.93%
Conteúdo do infoproduto (tema/relevância),22.67%,35.29%,75.00%,24.07%
Conteúdo gratuito oferecido pelo produtor,9.33%,23.53%,0.00%,5.56%
Garantia de devolução do dinheiro,0.00%,5.88%,0.00%,1.85%
Preço,6.67%,0.00%,0.00%,14.81%
"Qualidade da apresentação (vídeo, áudio, design, etc.)",17.33%,11.76%,25.00%,12.96%
Recomendações de amigos/familiares,20.00%,17.65%,0.00%,14.81%

------------------------------

Renda,"Acima de R$ 1.212 até R$ 3.636,00","Acima de R$ 3.636,00 até R$ 6.000",Acima de R$ 6.000,"Até R$ 1.212,00"
Primeiro Contato,,,,
"Pesquisa em mecanismos de busca, como o Google",24.00%,17.65%,25.00%,14.81%
"Por meio das redes sociais, como Instagram, TikTok, YouTube ou Twitter",34.67%,35.29%,50.00%,44.44%
"Por meio de anúncios online, como no Facebook ou Google Ads",10.67%,11.76%,0.00%,7.41%
Recomendação de amigos ou colegas,30.67%,35.29%,25.00%,33.33%

------------------------------

Renda,"Acima de R$ 1.212 até R$ 3.636,00","Acima de R$ 3.636,00 até R$ 6.000",Acima de R$ 6.000,"Até R$ 1.212,00"
Motivação para Compra,,,,
Aquisição de conhecimento específico,33.33%,35.29%,25.00%,22.22%
Desenvolvimento de habilidades técnicas,5.33%,17.65%,50.00%,11.11%
Empreendedorismo ou criação de negócio próprio,1.33%,0.00%,0.00%,0.00%
Facilidade de aprendizado online,6.67%,5.88%,0.00%,9.26%
Flexibilidade de horário de estudo,9.33%,5.88%,0.00%,12.96%
Ganhos financeiros,5.33%,11.76%,0.00%,5.56%
Indicação de colegas ou amigos,0.00%,0.00%,0.00%,7.41%
Mudar de Carreira (aprender uma nova profissão),12.00%,0.00%,0.00%,5.56%
"Preparação para exames, concursos ou certificações",18.67%,23.53%,0.00%,12.96%
Realização de objetivos de vida,8.00%,0.00%,0.00%,9.26%
Solução para um problema específico,0.00%,0.00%,25.00%,3.70%

------------------------------

Primeira Compra,Ainda não comprei,Antes da pandemia,Depois da pandemia,Durante a pandemia
Formato do Infoproduto,,,,
Texto: PDF e E-book,41.67%,31.65%,26.32%,30.00%
"Visual: Infográficos, figuras, página de vendas, site, Template e planilha",0.00%,6.33%,0.00%,7.50%
"Vídeo: Vídeo aulas, mentorias, screencasts , cursos e lives, Videocast , filmes ou documentários",50.00%,58.23%,73.68%,62.50%
Áudio: Áudiobook e podcast,8.33%,3.80%,0.00%,0.00%

------------------------------

Primeira Compra,Ainda não comprei,Antes da pandemia,Depois da pandemia,Durante a pandemia
Área mais Consumida,,,,
Desenvolvimento Pessoal,16.67%,21.52%,26.32%,30.00%
Educação,75.00%,60.76%,36.84%,55.00%
Finanças,0.00%,8.86%,10.53%,5.00%
Saúde,8.33%,8.86%,26.32%,10.00%

------------------------------

Primeira Compra,Ainda não comprei,Antes da pandemia,Depois da pandemia,Durante a pandemia
Disposição Financeira,,,,
"Acima de R$ 200,00",0.00%,30.38%,31.58%,22.50%
"Entre R$ 100,00 e R$ 200,00",8.33%,27.85%,26.32%,15.00%
"Entre R$ 50,00 e R$ 100,00.",66.67%,32.91%,21.05%,52.50%
"Menos de R$ 50,00",25.00%,8.86%,21.05%,10.00%

------------------------------

Primeira Compra,Ainda não comprei,Antes da pandemia,Depois da pandemia,Durante a pandemia
Influência na Compra,,,,
Avaliações e depoimentos de clientes,25.00%,22.78%,31.58%,15.00%
Conteúdo do infoproduto (tema/relevância),8.33%,27.85%,21.05%,30.00%
Conteúdo gratuito oferecido pelo produtor,0.00%,10.13%,5.26%,12.50%
Garantia de devolução do dinheiro,0.00%,1.27%,0.00%,2.50%
Preço,25.00%,5.06%,10.53%,10.00%
"Qualidade da apresentação (vídeo, áudio, design, etc.)",8.33%,18.99%,10.53%,12.50%
Recomendações de amigos/familiares,33.33%,13.92%,21.05%,17.50%

------------------------------

Primeira Compra,Ainda não comprei,Antes da pandemia,Depois da pandemia,Durante a pandemia
Primeiro Contato,,,,
"Pesquisa em mecanismos de busca, como o Google",8.33%,24.05%,21.05%,15.00%
"Por meio das redes sociais, como Instagram, TikTok, YouTube ou Twitter",25.00%,39.24%,36.84%,42.50%
"Por meio de anúncios online, como no Facebook ou Google Ads",0.00%,7.59%,10.53%,15.00%
Recomendação de amigos ou colegas,66.67%,29.11%,31.58%,27.50%

------------------------------

Primeira Compra,Ainda não comprei,Antes da pandemia,Depois da pandemia,Durante a pandemia
Motivação para Compra,,,,
Aquisição de conhecimento específico,25.00%,32.91%,10.53%,32.50%
Desenvolvimento de habilidades técnicas,16.67%,11.39%,15.79%,2.50%
Empreendedorismo ou criação de negócio próprio,0.00%,1.27%,0.00%,0.00%
Facilidade de aprendizado online,0.00%,7.59%,0.00%,12.50%
Flexibilidade de horário de estudo,8.33%,13.92%,5.26%,5.00%
Ganhos financeiros,16.67%,5.06%,10.53%,2.50%
Indicação de colegas ou amigos,16.67%,1.27%,0.00%,2.50%
Mudar de Carreira (aprender uma nova profissão),0.00%,6.33%,26.32%,5.00%
"Preparação para exames, concursos ou certificações",0.00%,12.66%,26.32%,25.00%
Realização de objetivos de vida,8.33%,6.33%,0.00%,12.50%
Solução para um problema específico,8.33%,1.27%,5.26%,0.00%

------------------------------

Formato do Infoproduto,Texto: PDF e E-book,"Visual: Infográficos, figuras, página de vendas, site, Template e planilha","Vídeo: Vídeo aulas, mentorias, screencasts , cursos e lives, Videocast , filmes ou documentários",Áudio: Áudiobook e podcast
Área mais Consumida,,,,
Desenvolvimento Pessoal,17.02%,37.50%,25.27%,50.00%
Educação,63.83%,50.00%,54.95%,50.00%
Finanças,4.26%,12.50%,8.79%,0.00%
Saúde,14.89%,0.00%,10.99%,0.00%

------------------------------

Formato do Infoproduto,Texto: PDF e E-book,"Visual: Infográficos, figuras, página de vendas, site, Template e planilha","Vídeo: Vídeo aulas, mentorias, screencasts , cursos e lives, Videocast , filmes ou documentários",Áudio: Áudiobook e podcast
Disposição Financeira,,,,
"Acima de R$ 200,00",17.02%,0.00%,32.97%,25.00%
"Entre R$ 100,00 e R$ 200,00",17.02%,25.00%,24.18%,50.00%
"Entre R$ 50,00 e R$ 100,00.",51.06%,62.50%,32.97%,0.00%
"Menos de R$ 50,00",14.89%,12.50%,9.89%,25.00%

------------------------------

Formato do Infoproduto,Texto: PDF e E-book,"Visual: Infográficos, figuras, página de vendas, site, Template e planilha","Vídeo: Vídeo aulas, mentorias, screencasts , cursos e lives, Videocast , filmes ou documentários",Áudio: Áudiobook e podcast
Influência na Compra,,,,
Avaliações e depoimentos de clientes,27.66%,37.50%,18.68%,0.00%
Conteúdo do infoproduto (tema/relevância),27.66%,37.50%,25.27%,0.00%
Conteúdo gratuito oferecido pelo produtor,8.51%,0.00%,8.79%,50.00%
Garantia de devolução do dinheiro,0.00%,0.00%,2.20%,0.00%
Preço,12.77%,12.50%,6.59%,0.00%
"Qualidade da apresentação (vídeo, áudio, design, etc.)",10.64%,0.00%,18.68%,25.00%
Recomendações de amigos/familiares,12.77%,12.50%,19.78%,25.00%

------------------------------

Formato do Infoproduto,Texto: PDF e E-book,"Visual: Infográficos, figuras, página de vendas, site, Template e planilha","Vídeo: Vídeo aulas, mentorias, screencasts , cursos e lives, Videocast , filmes ou documentários",Áudio: Áudiobook e podcast
Primeiro Contato,,,,
"Pesquisa em mecanismos de busca, como o Google",31.91%,37.50%,13.19%,0.00%
"Por meio das redes sociais, como Instagram, TikTok, YouTube ou Twitter",31.91%,25.00%,42.86%,50.00%
"Por meio de anúncios online, como no Facebook ou Google Ads",6.38%,12.50%,9.89%,25.00%
Recomendação de amigos ou colegas,29.79%,25.00%,34.07%,25.00%

------------------------------

Formato do Infoproduto,Texto: PDF e E-book,"Visual: Infográficos, figuras, página de vendas, site, Template e planilha","Vídeo: Vídeo aulas, mentorias, screencasts , cursos e lives, Videocast , filmes ou documentários",Áudio: Áudiobook e podcast
Motivação para Compra,,,,
Aquisição de conhecimento específico,44.68%,0.00%,23.08%,50.00%
Desenvolvimento de habilidades técnicas,6.38%,0.00%,12.09%,25.00%
Empreendedorismo ou criação de negócio próprio,0.00%,0.00%,1.10%,0.00%
Facilidade de aprendizado online,4.26%,25.00%,7.69%,0.00%
Flexibilidade de horário de estudo,10.64%,0.00%,10.99%,0.00%
Ganhos financeiros,2.13%,25.00%,5.49%,25.00%
Indicação de colegas ou amigos,4.26%,12.50%,1.10%,0.00%
Mudar de Carreira (aprender uma nova profissão),8.51%,12.50%,7.69%,0.00%
"Preparação para exames, concursos ou certificações",12.77%,12.50%,19.78%,0.00%
Realização de objetivos de vida,4.26%,12.50%,8.79%,0.00%
Solução para um problema específico,2.13%,0.00%,2.20%,0.00%

------------------------------

Área mais Consumida         Desenvolvimento Pessoal Educação Finanças   Saúde
Disposição Financeira
Acima de R$ 200,00                           22.22%   30.23%   18.18%  17.65%
Entre R$ 100,00 e R$ 200,00                  22.22%   22.09%   36.36%  17.65%
Entre R$ 50,00 e R$ 100,00.                  41.67%   37.21%   36.36%  47.06%
Menos de R$ 50,00                            13.89%   10.47%    9.09%  17.65%

------------------------------

Área mais Consumida,Desenvolvimento Pessoal,Educação,Finanças,Saúde
Influência na Compra,,,,
Avaliações e depoimentos de clientes,30.56%,23.26%,0.00%,11.76%
Conteúdo do infoproduto (tema/relevância),33.33%,29.07%,9.09%,5.88%
Conteúdo gratuito oferecido pelo produtor,11.11%,10.47%,9.09%,0.00%
Garantia de devolução do dinheiro,0.00%,0.00%,9.09%,5.88%
Preço,5.56%,5.81%,9.09%,29.41%
"Qualidade da apresentação (vídeo, áudio, design, etc.)",5.56%,18.60%,36.36%,5.88%
Recomendações de amigos/familiares,13.89%,12.79%,27.27%,41.18%

------------------------------

Área mais Consumida,Desenvolvimento Pessoal,Educação,Finanças,Saúde
Primeiro Contato,,,,
"Pesquisa em mecanismos de busca, como o Google",25.00%,23.26%,0.00%,5.88%
"Por meio das redes sociais, como Instagram, TikTok, YouTube ou Twitter",41.67%,36.05%,63.64%,29.41%
"Por meio de anúncios online, como no Facebook ou Google Ads",11.11%,8.14%,9.09%,11.76%
Recomendação de amigos ou colegas,22.22%,32.56%,27.27%,52.94%

------------------------------

Área mais Consumida,Desenvolvimento Pessoal,Educação,Finanças,Saúde
Motivação para Compra,,,,
Aquisição de conhecimento específico,22.22%,33.72%,18.18%,29.41%
Desenvolvimento de habilidades técnicas,25.00%,5.81%,0.00%,5.88%
Empreendedorismo ou criação de negócio próprio,2.78%,0.00%,0.00%,0.00%
Facilidade de aprendizado online,5.56%,6.98%,18.18%,5.88%
Flexibilidade de horário de estudo,2.78%,11.63%,0.00%,23.53%
Ganhos financeiros,5.56%,4.65%,27.27%,0.00%
Indicação de colegas ou amigos,5.56%,2.33%,0.00%,0.00%
Mudar de Carreira (aprender uma nova profissão),5.56%,8.14%,18.18%,5.88%
"Preparação para exames, concursos ou certificações",13.89%,18.60%,18.18%,11.76%
Realização de objetivos de vida,11.11%,5.81%,0.00%,11.76%
Solução para um problema específico,0.00%,2.33%,0.00%,5.88%

------------------------------

Disposição Financeira,"Acima de R$ 200,00","Entre R$ 100,00 e R$ 200,00","Entre R$ 50,00 e R$ 100,00.","Menos de R$ 50,00"
Influência na Compra,,,,
Avaliações e depoimentos de clientes,17.95%,29.41%,23.73%,11.11%
Conteúdo do infoproduto (tema/relevância),35.90%,29.41%,20.34%,16.67%
Conteúdo gratuito oferecido pelo produtor,15.38%,5.88%,5.08%,16.67%
Garantia de devolução do dinheiro,2.56%,2.94%,0.00%,0.00%
Preço,2.56%,2.94%,11.86%,22.22%
"Qualidade da apresentação (vídeo, áudio, design, etc.)",15.38%,14.71%,20.34%,0.00%
Recomendações de amigos/familiares,10.26%,14.71%,18.64%,33.33%

------------------------------

Disposição Financeira,"Acima de R$ 200,00","Entre R$ 100,00 e R$ 200,00","Entre R$ 50,00 e R$ 100,00.","Menos de R$ 50,00"
Primeiro Contato,,,,
"Pesquisa em mecanismos de busca, como o Google",28.21%,17.65%,18.64%,11.11%
"Por meio das redes sociais, como Instagram, TikTok, YouTube ou Twitter",41.03%,47.06%,33.90%,33.33%
"Por meio de anúncios online, como no Facebook ou Google Ads",10.26%,5.88%,10.17%,11.11%
Recomendação de amigos ou colegas,20.51%,29.41%,37.29%,44.44%

------------------------------

Disposição Financeira,"Acima de R$ 200,00","Entre R$ 100,00 e R$ 200,00","Entre R$ 50,00 e R$ 100,00.","Menos de R$ 50,00"
Motivação para Compra,,,,
Aquisição de conhecimento específico,20.51%,35.29%,33.90%,22.22%
Desenvolvimento de habilidades técnicas,15.38%,8.82%,8.47%,5.56%
Empreendedorismo ou criação de negócio próprio,0.00%,2.94%,0.00%,0.00%
Facilidade de aprendizado online,7.69%,11.76%,6.78%,0.00%
Flexibilidade de horário de estudo,5.13%,11.76%,13.56%,5.56%
Ganhos financeiros,0.00%,8.82%,6.78%,11.11%
Indicação de colegas ou amigos,0.00%,0.00%,3.39%,11.11%
Mudar de Carreira (aprender uma nova profissão),10.26%,8.82%,3.39%,16.67%
"Preparação para exames, concursos ou certificações",30.77%,8.82%,13.56%,11.11%
Realização de objetivos de vida,10.26%,2.94%,8.47%,5.56%
Solução para um problema específico,0.00%,0.00%,1.69%,11.11%

------------------------------

Influência na Compra,Avaliações e depoimentos de clientes,Conteúdo do infoproduto (tema/relevância),Conteúdo gratuito oferecido pelo produtor,Garantia de devolução do dinheiro,Preço,"Qualidade da apresentação (vídeo, áudio, design, etc.)",Recomendações de amigos/familiares
Primeiro Contato,,,,,,,
"Pesquisa em mecanismos de busca, como o Google",36.36%,25.64%,14.29%,0.00%,7.69%,17.39%,3.85%
"Por meio das redes sociais, como Instagram, TikTok, YouTube ou Twitter",45.45%,41.03%,42.86%,100.00%,38.46%,47.83%,11.54%
"Por meio de anúncios online, como no Facebook ou Google Ads",3.03%,10.26%,28.57%,0.00%,0.00%,8.70%,11.54%
Recomendação de amigos ou colegas,15.15%,23.08%,14.29%,0.00%,53.85%,26.09%,73.08%

------------------------------

Influência na Compra,Avaliações e depoimentos de clientes,Conteúdo do infoproduto (tema/relevância),Conteúdo gratuito oferecido pelo produtor,Garantia de devolução do dinheiro,Preço,"Qualidade da apresentação (vídeo, áudio, design, etc.)",Recomendações de amigos/familiares
Motivação para Compra,,,,,,,
Aquisição de conhecimento específico,21.21%,33.33%,50.00%,0.00%,15.38%,43.48%,19.23%
Desenvolvimento de habilidades técnicas,15.15%,12.82%,7.14%,0.00%,7.69%,8.70%,3.85%
Empreendedorismo ou criação de negócio próprio,0.00%,2.56%,0.00%,0.00%,0.00%,0.00%,0.00%
Facilidade de aprendizado online,12.12%,5.13%,7.14%,0.00%,0.00%,4.35%,11.54%
Flexibilidade de horário de estudo,18.18%,10.26%,0.00%,0.00%,15.38%,4.35%,7.69%
Ganhos financeiros,3.03%,2.56%,0.00%,50.00%,7.69%,8.70%,11.54%
Indicação de colegas ou amigos,0.00%,2.56%,0.00%,0.00%,15.38%,0.00%,3.85%
Mudar de Carreira (aprender uma nova profissão),3.03%,7.69%,14.29%,0.00%,7.69%,13.04%,7.69%
"Preparação para exames, concursos ou certificações",21.21%,15.38%,7.14%,50.00%,0.00%,17.39%,23.08%
Realização de objetivos de vida,6.06%,5.13%,14.29%,0.00%,23.08%,0.00%,7.69%
Solução para um problema específico,0.00%,2.56%,0.00%,0.00%,7.69%,0.00%,3.85%

------------------------------

Primeiro Contato,"Pesquisa em mecanismos de busca, como o Google","Por meio das redes sociais, como Instagram, TikTok, YouTube ou Twitter","Por meio de anúncios online, como no Facebook ou Google Ads",Recomendação de amigos ou colegas
Motivação para Compra,,,,
Aquisição de conhecimento específico,40.00%,25.86%,50.00%,20.83%
Desenvolvimento de habilidades técnicas,13.33%,8.62%,0.00%,12.50%
Empreendedorismo ou criação de negócio próprio,0.00%,0.00%,7.14%,0.00%
Facilidade de aprendizado online,10.00%,10.34%,7.14%,2.08%
Flexibilidade de horário de estudo,6.67%,12.07%,0.00%,12.50%
Ganhos financeiros,0.00%,6.90%,14.29%,6.25%
Indicação de colegas ou amigos,3.33%,1.72%,0.00%,4.17%
Mudar de Carreira (aprender uma nova profissão),6.67%,8.62%,21.43%,4.17%
"Preparação para exames, concursos ou certificações",13.33%,17.24%,0.00%,22.92%
Realização de objetivos de vida,6.67%,5.17%,0.00%,12.50%
Solução para um problema específico,0.00%,3.45%,0.00%,2.08%

------------------------------

In [59]:
for col_qualy in qualy.columns:
    for col_quanty in quanty.columns:
        if col_qualy != col_quanty:
            result = df.groupby(by=col_qualy)[col_quanty].agg(
                Média='mean', Mediana='median', DesvPad='std').applymap('{:.2}'.format)
            result = result.rename_axis(col_quanty, axis=1)
            display(result)
            print('\n' + '-'*30 + '\n')

Frequência no Consumo Média Mediana DesvPad
Gênero
Feminino                3.2     3.0     1.3
Masculino               3.4     3.5     1.3

------------------------------

Benefícios da Mentoria Média Mediana DesvPad
Gênero
Feminino                 4.1     4.0     1.0
Masculino                4.0     4.0    0.83

------------------------------

Meta Melhora o Progresso Média Mediana DesvPad
Gênero
Feminino                   4.2     4.0    0.92
Masculino                  4.1     4.0    0.86

------------------------------

Variedade Melhora a Experiência Média Mediana DesvPad
Gênero
Feminino                          4.5     5.0    0.75
Masculino                         4.4     5.0     0.8

------------------------------

Satisfação com o Produto Média Mediana DesvPad
Gênero
Feminino                   4.0     4.0    0.98
Masculino                  3.7     4.0    0.85

------------------------------

Percepção da Experiência com o Produto Média Mediana DesvPad
Gênero
Feminino                                 4.1     4.0    0.87
Masculino                                3.9     4.0    0.76

------------------------------

Indicaria o Produto Média Mediana DesvPad
Gênero
Feminino              4.1     4.0    0.98
Masculino             3.8     4.0    0.83

------------------------------

Frequência no Consumo Média Mediana DesvPad
Idade
18-24 anos              3.2     3.0     1.3
25-34 anos              3.6     4.0     1.3
35-44 anos              3.2     3.0     1.2
45 anos ou mais         1.8     1.0     1.5

------------------------------

Benefícios da Mentoria Média Mediana DesvPad
Idade
18-24 anos               4.0     4.0    0.99
25-34 anos               4.1     4.0    0.86
35-44 anos               3.9     4.0    0.97
45 anos ou mais          4.8     5.0     0.5

------------------------------

Meta Melhora o Progresso Média Mediana DesvPad
Idade
18-24 anos                 4.2     4.0     0.9
25-34 anos                 4.2     4.0    0.83
35-44 anos                 3.9     4.0     1.0
45 anos ou mais            4.2     4.5    0.96

------------------------------

Variedade Melhora a Experiência Média Mediana DesvPad
Idade
18-24 anos                        4.4     5.0    0.82
25-34 anos                        4.6     5.0    0.63
35-44 anos                        4.3     5.0    0.93
45 anos ou mais                   4.2     4.5    0.96

------------------------------

Satisfação com o Produto Média Mediana DesvPad
Idade
18-24 anos                 4.0     4.0    0.88
25-34 anos                 3.9     4.0    0.97
35-44 anos                 3.7     4.0     1.0
45 anos ou mais            3.8     3.5    0.96

------------------------------

Percepção da Experiência com o Produto Média Mediana DesvPad
Idade
18-24 anos                               4.1     4.0    0.79
25-34 anos                               3.9     4.0    0.86
35-44 anos                               3.9     4.0    0.81
45 anos ou mais                          4.5     5.0     1.0

------------------------------

Indicaria o Produto Média Mediana DesvPad
Idade
18-24 anos            4.1     4.0    0.87
25-34 anos            4.0     4.0     1.0
35-44 anos            3.8     4.0     1.0
45 anos ou mais       3.8     4.0     0.5

------------------------------

Frequência no Consumo Média Mediana DesvPad
Escolaridade
Ensino Fundamental      1.0     1.0     nan
Ensino Médio            3.0     3.0     1.4
Ensino Superior         3.3     3.0     1.3
Pós-Graduação           4.2     4.0    0.79

------------------------------

Benefícios da Mentoria Média Mediana DesvPad
Escolaridade
Ensino Fundamental       4.0     4.0     nan
Ensino Médio             4.2     4.0    0.85
Ensino Superior          3.9     4.0     1.0
Pós-Graduação            4.1     4.0    0.83

------------------------------

Meta Melhora o Progresso Média Mediana DesvPad
Escolaridade
Ensino Fundamental         4.0     4.0     nan
Ensino Médio               4.3     4.0    0.87
Ensino Superior            4.1     4.0    0.92
Pós-Graduação              3.9     4.0    0.87

------------------------------

Variedade Melhora a Experiência Média Mediana DesvPad
Escolaridade
Ensino Fundamental                4.0     4.0     nan
Ensino Médio                      4.5     5.0    0.86
Ensino Superior                   4.4     5.0    0.76
Pós-Graduação                     4.7     5.0    0.46

------------------------------

Satisfação com o Produto Média Mediana DesvPad
Escolaridade
Ensino Fundamental         3.0     3.0     nan
Ensino Médio               3.8     4.0     1.0
Ensino Superior            3.8     4.0    0.88
Pós-Graduação              4.3     5.0    0.84

------------------------------

Percepção da Experiência com o Produto Média Mediana DesvPad
Escolaridade
Ensino Fundamental                       5.0     5.0     nan
Ensino Médio                             3.9     4.0    0.87
Ensino Superior                          4.0     4.0    0.79
Pós-Graduação                            4.1     4.0    0.83

------------------------------

Indicaria o Produto Média Mediana DesvPad
Escolaridade
Ensino Fundamental    4.0     4.0     nan
Ensino Médio          3.9     4.0    0.95
Ensino Superior       4.0     4.0    0.95
Pós-Graduação         4.3     4.5    0.77

------------------------------

Frequência no Consumo Média Mediana DesvPad
Estado Civil
Casado(a)               3.5     4.0     1.3
Divorciado(a)           3.5     3.5    0.71
Outros                  3.8     4.0     1.3
Solteiro(a)             3.2     3.0     1.3
Viúvo(a)                2.0     2.0     nan

------------------------------

Benefícios da Mentoria Média Mediana DesvPad
Estado Civil
Casado(a)                4.2     4.0     0.8
Divorciado(a)            4.0     4.0     1.4
Outros                   4.0     4.0     1.2
Solteiro(a)              4.0     4.0    0.97
Viúvo(a)                 5.0     5.0     nan

------------------------------

Meta Melhora o Progresso Média Mediana DesvPad
Estado Civil
Casado(a)                  4.0     4.0    0.94
Divorciado(a)              4.0     4.0     1.4
Outros                     4.5     4.5    0.58
Solteiro(a)                4.2     4.0    0.88
Viúvo(a)                   5.0     5.0     nan

------------------------------

Variedade Melhora a Experiência Média Mediana DesvPad
Estado Civil
Casado(a)                         4.5     5.0     0.7
Divorciado(a)                     3.5     3.5     2.1
Outros                            5.0     5.0     0.0
Solteiro(a)                       4.5     5.0    0.78
Viúvo(a)                          5.0     5.0     nan

------------------------------

Satisfação com o Produto Média Mediana DesvPad
Estado Civil
Casado(a)                  4.1     4.0     1.0
Divorciado(a)              3.0     3.0     0.0
Outros                     4.2     4.5    0.96
Solteiro(a)                3.8     4.0    0.91
Viúvo(a)                   5.0     5.0     nan

------------------------------

Percepção da Experiência com o Produto Média Mediana DesvPad
Estado Civil
Casado(a)                                4.1     4.0    0.92
Divorciado(a)                            3.5     3.5    0.71
Outros                                   4.2     4.0     0.5
Solteiro(a)                              3.9     4.0    0.81
Viúvo(a)                                 4.0     4.0     nan

------------------------------

Indicaria o Produto Média Mediana DesvPad
Estado Civil
Casado(a)             4.2     4.0    0.86
Divorciado(a)         2.5     2.5    0.71
Outros                4.5     4.5    0.58
Solteiro(a)           3.9     4.0    0.95
Viúvo(a)              4.0     4.0     nan

------------------------------

Frequência no Consumo             Média Mediana DesvPad
Renda
Acima de R$ 1.212 até R$ 3.636,00   3.4     3.0     1.2
Acima de R$ 3.636,00 até R$ 6.000   3.6     4.0     1.3
Acima de R$ 6.000                   3.2     3.0     1.5
Até R$ 1.212,00                     3.0     3.0     1.4

------------------------------

Benefícios da Mentoria            Média Mediana DesvPad
Renda
Acima de R$ 1.212 até R$ 3.636,00   3.9     4.0    0.91
Acima de R$ 3.636,00 até R$ 6.000   4.5     5.0     0.8
Acima de R$ 6.000                   3.5     3.5     1.7
Até R$ 1.212,00                     4.2     4.0    0.91

------------------------------

Meta Melhora o Progresso          Média Mediana DesvPad
Renda
Acima de R$ 1.212 até R$ 3.636,00   4.1     4.0    0.84
Acima de R$ 3.636,00 até R$ 6.000   3.8     4.0     1.0
Acima de R$ 6.000                   4.0     4.5     1.4
Até R$ 1.212,00                     4.4     5.0    0.85

------------------------------

Variedade Melhora a Experiência   Média Mediana DesvPad
Renda
Acima de R$ 1.212 até R$ 3.636,00   4.5     5.0    0.78
Acima de R$ 3.636,00 até R$ 6.000   4.4     5.0    0.71
Acima de R$ 6.000                   4.0     4.0     1.2
Até R$ 1.212,00                     4.5     5.0    0.77

------------------------------

Satisfação com o Produto          Média Mediana DesvPad
Renda
Acima de R$ 1.212 até R$ 3.636,00   3.9     4.0    0.81
Acima de R$ 3.636,00 até R$ 6.000   3.9     4.0    0.97
Acima de R$ 6.000                   3.8     4.0     1.3
Até R$ 1.212,00                     3.9     4.0     1.1

------------------------------

Percepção da Experiência com o Produto Média Mediana DesvPad
Renda
Acima de R$ 1.212 até R$ 3.636,00        4.0     4.0    0.73
Acima de R$ 3.636,00 até R$ 6.000        3.8     4.0    0.95
Acima de R$ 6.000                        3.8     4.0     1.3
Até R$ 1.212,00                          4.0     4.0    0.89

------------------------------

Indicaria o Produto               Média Mediana DesvPad
Renda
Acima de R$ 1.212 até R$ 3.636,00   4.0     4.0     0.8
Acima de R$ 3.636,00 até R$ 6.000   3.9     4.0    0.99
Acima de R$ 6.000                   3.5     4.0     1.7
Até R$ 1.212,00                     4.0     4.0     1.0

------------------------------

Frequência no Consumo Média Mediana DesvPad
Primeira Compra
Ainda não comprei       2.0     2.0    0.95
Antes da pandemia       3.5     4.0     1.2
Depois da pandemia      3.5     3.0     1.1
Durante a pandemia      3.1     3.0     1.4

------------------------------

Benefícios da Mentoria Média Mediana DesvPad
Primeira Compra
Ainda não comprei        4.2     4.5    0.94
Antes da pandemia        4.0     4.0    0.99
Depois da pandemia       4.4     5.0    0.76
Durante a pandemia       3.9     4.0    0.89

------------------------------

Meta Melhora o Progresso Média Mediana DesvPad
Primeira Compra
Ainda não comprei          4.3     4.0    0.65
Antes da pandemia          4.1     4.0    0.89
Depois da pandemia         4.4     5.0     1.1
Durante a pandemia         4.0     4.0    0.85

------------------------------

Variedade Melhora a Experiência Média Mediana DesvPad
Primeira Compra
Ainda não comprei                 4.2     4.0    0.75
Antes da pandemia                 4.6     5.0    0.71
Depois da pandemia                4.3     5.0     1.1
Durante a pandemia                4.5     5.0    0.71

------------------------------

Satisfação com o Produto Média Mediana DesvPad
Primeira Compra
Ainda não comprei          3.4     3.5     1.2
Antes da pandemia          3.9     4.0    0.84
Depois da pandemia         4.2     5.0     1.0
Durante a pandemia         3.8     4.0    0.96

------------------------------

Percepção da Experiência com o Produto Média Mediana DesvPad
Primeira Compra
Ainda não comprei                        3.7     4.0     1.1
Antes da pandemia                        3.9     4.0    0.78
Depois da pandemia                       4.2     4.0    0.92
Durante a pandemia                       4.0     4.0    0.78

------------------------------

Indicaria o Produto Média Mediana DesvPad
Primeira Compra
Ainda não comprei     3.8     4.0     1.0
Antes da pandemia     3.9     4.0    0.85
Depois da pandemia    4.1     5.0     1.2
Durante a pandemia    4.2     4.0    0.89

------------------------------

Frequência no Consumo                              Média Mediana DesvPad
Formato do Infoproduto
Texto: PDF e E-book                                  3.2     3.0     1.3
Visual: Infográficos, figuras, página de vendas...   3.4     3.0     1.4
Vídeo: Vídeo aulas, mentorias, screencasts , cu...   3.3     3.0     1.3
Áudio: Áudiobook e podcast                           3.0     2.5     1.4

------------------------------

Benefícios da Mentoria                             Média Mediana DesvPad
Formato do Infoproduto
Texto: PDF e E-book                                  3.9     4.0     1.0
Visual: Infográficos, figuras, página de vendas...   3.4     3.0    0.52
Vídeo: Vídeo aulas, mentorias, screencasts , cu...   4.2     4.0    0.88
Áudio: Áudiobook e podcast                           4.5     5.0     1.0

------------------------------

Meta Melhora o Progresso                           Média Mediana DesvPad
Formato do Infoproduto
Texto: PDF e E-book                                  4.1     4.0     0.8
Visual: Infográficos, figuras, página de vendas...   3.0     3.0    0.93
Vídeo: Vídeo aulas, mentorias, screencasts , cu...   4.3     4.0    0.88
Áudio: Áudiobook e podcast                           4.8     5.0     0.5

------------------------------

Variedade Melhora a Experiência                    Média Mediana DesvPad
Formato do Infoproduto
Texto: PDF e E-book                                  4.4     5.0    0.74
Visual: Infográficos, figuras, página de vendas...   4.1     4.5    0.99
Vídeo: Vídeo aulas, mentorias, screencasts , cu...   4.5     5.0    0.78
Áudio: Áudiobook e podcast                           4.8     5.0     0.5

------------------------------

Satisfação com o Produto                           Média Mediana DesvPad
Formato do Infoproduto
Texto: PDF e E-book                                  3.8     4.0    0.84
Visual: Infográficos, figuras, página de vendas...   3.5     3.0    0.76
Vídeo: Vídeo aulas, mentorias, screencasts , cu...   4.0     4.0    0.97
Áudio: Áudiobook e podcast                           3.8     4.0     1.3

------------------------------

Percepção da Experiência com o Produto             Média Mediana DesvPad
Formato do Infoproduto
Texto: PDF e E-book                                  3.9     4.0    0.78
Visual: Infográficos, figuras, página de vendas...   3.6     3.5    0.74
Vídeo: Vídeo aulas, mentorias, screencasts , cu...   4.1     4.0    0.84
Áudio: Áudiobook e podcast                           3.5     4.0     1.0

------------------------------

Indicaria o Produto                                Média Mediana DesvPad
Formato do Infoproduto
Texto: PDF e E-book                                  3.8     4.0    0.99
Visual: Infográficos, figuras, página de vendas...   3.6     3.5    0.74
Vídeo: Vídeo aulas, mentorias, screencasts , cu...   4.1     4.0    0.89
Áudio: Áudiobook e podcast                           3.8     4.0     1.3

------------------------------

Frequência no Consumo   Média Mediana DesvPad
Área mais Consumida
Desenvolvimento Pessoal   3.6     3.5     1.2
Educação                  3.3     3.0     1.4
Finanças                  3.3     4.0     1.2
Saúde                     2.9     3.0     1.2

------------------------------

Benefícios da Mentoria  Média Mediana DesvPad
Área mais Consumida
Desenvolvimento Pessoal   3.9     4.0    0.83
Educação                  4.1     4.0    0.93
Finanças                  3.5     3.0     1.2
Saúde                     4.1     4.0    0.99

------------------------------

Meta Melhora o Progresso Média Mediana DesvPad
Área mais Consumida
Desenvolvimento Pessoal    4.1     4.0    0.98
Educação                   4.2     4.0    0.79
Finanças                   3.8     4.0     1.3
Saúde                      4.2     4.0    0.83

------------------------------

Variedade Melhora a Experiência Média Mediana DesvPad
Área mais Consumida
Desenvolvimento Pessoal           4.4     5.0    0.87
Educação                          4.5     5.0    0.71
Finanças                          4.5     5.0    0.69
Saúde                             4.5     5.0    0.94

------------------------------

Satisfação com o Produto Média Mediana DesvPad
Área mais Consumida
Desenvolvimento Pessoal    3.9     4.0    0.87
Educação                   4.0     4.0    0.96
Finanças                   3.8     4.0    0.98
Saúde                      3.6     3.0    0.87

------------------------------

Percepção da Experiência com o Produto Média Mediana DesvPad
Área mais Consumida
Desenvolvimento Pessoal                  3.9     4.0    0.75
Educação                                 4.0     4.0    0.85
Finanças                                 3.7     4.0    0.79
Saúde                                    3.8     4.0    0.88

------------------------------

Indicaria o Produto     Média Mediana DesvPad
Área mais Consumida
Desenvolvimento Pessoal   3.9     4.0    0.87
Educação                  4.1     4.0     0.9
Finanças                  3.8     4.0    0.87
Saúde                     3.9     4.0     1.2

------------------------------

Frequência no Consumo       Média Mediana DesvPad
Disposição Financeira
Acima de R$ 200,00            3.8     4.0     1.2
Entre R$ 100,00 e R$ 200,00   3.4     3.5     1.2
Entre R$ 50,00 e R$ 100,00.   3.1     3.0     1.3
Menos de R$ 50,00             2.7     3.0     1.2

------------------------------

Benefícios da Mentoria      Média Mediana DesvPad
Disposição Financeira
Acima de R$ 200,00            4.1     4.0     1.0
Entre R$ 100,00 e R$ 200,00   4.1     4.0    0.92
Entre R$ 50,00 e R$ 100,00.   4.1     4.0    0.92
Menos de R$ 50,00             3.9     4.0    0.96

------------------------------

Meta Melhora o Progresso    Média Mediana DesvPad
Disposição Financeira
Acima de R$ 200,00            4.1     4.0    0.88
Entre R$ 100,00 e R$ 200,00   4.1     4.0    0.88
Entre R$ 50,00 e R$ 100,00.   4.3     4.0    0.79
Menos de R$ 50,00             3.9     4.0     1.2

------------------------------

Variedade Melhora a Experiência Média Mediana DesvPad
Disposição Financeira
Acima de R$ 200,00                4.6     5.0    0.75
Entre R$ 100,00 e R$ 200,00       4.6     5.0     0.6
Entre R$ 50,00 e R$ 100,00.       4.4     5.0    0.86
Menos de R$ 50,00                 4.2     4.0    0.79

------------------------------

Satisfação com o Produto    Média Mediana DesvPad
Disposição Financeira
Acima de R$ 200,00            4.0     4.0     1.0
Entre R$ 100,00 e R$ 200,00   3.9     4.0    0.89
Entre R$ 50,00 e R$ 100,00.   3.9     4.0    0.83
Menos de R$ 50,00             3.4     3.0     1.0

------------------------------

Percepção da Experiência com o Produto Média Mediana DesvPad
Disposição Financeira
Acima de R$ 200,00                       4.2     4.0    0.89
Entre R$ 100,00 e R$ 200,00              3.9     4.0    0.71
Entre R$ 50,00 e R$ 100,00.              4.0     4.0    0.74
Menos de R$ 50,00                        3.6     4.0     1.0

------------------------------

Indicaria o Produto         Média Mediana DesvPad
Disposição Financeira
Acima de R$ 200,00            4.3     5.0    0.89
Entre R$ 100,00 e R$ 200,00   3.9     4.0    0.87
Entre R$ 50,00 e R$ 100,00.   4.0     4.0    0.76
Menos de R$ 50,00             3.4     3.0     1.3

------------------------------

Frequência no Consumo                              Média Mediana DesvPad
Influência na Compra
Avaliações e depoimentos de clientes                 3.7     3.0     1.1
Conteúdo do infoproduto (tema/relevância)            3.4     3.0     1.3
Conteúdo gratuito oferecido pelo produtor            3.9     4.0     1.0
Garantia de devolução do dinheiro                    3.0     3.0     0.0
Preço                                                2.5     3.0     1.1
Qualidade da apresentação (vídeo, áudio, design...   3.4     4.0     1.3
Recomendações de amigos/familiares                   2.7     3.0     1.5

------------------------------

Benefícios da Mentoria                             Média Mediana DesvPad
Influência na Compra
Avaliações e depoimentos de clientes                 4.0     4.0    0.83
Conteúdo do infoproduto (tema/relevância)            4.0     4.0     1.1
Conteúdo gratuito oferecido pelo produtor            4.4     5.0    0.85
Garantia de devolução do dinheiro                    5.0     5.0     0.0
Preço                                                3.5     3.0    0.88
Qualidade da apresentação (vídeo, áudio, design...   4.1     4.0    0.95
Recomendações de amigos/familiares                   4.0     4.0    0.89

------------------------------

Meta Melhora o Progresso                           Média Mediana DesvPad
Influência na Compra
Avaliações e depoimentos de clientes                 4.3     4.0    0.72
Conteúdo do infoproduto (tema/relevância)            4.0     4.0    0.97
Conteúdo gratuito oferecido pelo produtor            4.3     4.5    0.83
Garantia de devolução do dinheiro                    4.5     4.5    0.71
Preço                                                3.9     4.0    0.95
Qualidade da apresentação (vídeo, áudio, design...   4.2     5.0     1.1
Recomendações de amigos/familiares                   4.3     4.0    0.78

------------------------------

Variedade Melhora a Experiência                    Média Mediana DesvPad
Influência na Compra
Avaliações e depoimentos de clientes                 4.7     5.0    0.65
Conteúdo do infoproduto (tema/relevância)            4.5     5.0    0.72
Conteúdo gratuito oferecido pelo produtor            4.3     4.5    0.83
Garantia de devolução do dinheiro                    4.5     4.5    0.71
Preço                                                3.8     4.0    0.93
Qualidade da apresentação (vídeo, áudio, design...   4.7     5.0    0.76
Recomendações de amigos/familiares                   4.4     5.0    0.75

------------------------------

Satisfação com o Produto                           Média Mediana DesvPad
Influência na Compra
Avaliações e depoimentos de clientes                 4.1     4.0    0.74
Conteúdo do infoproduto (tema/relevância)            4.0     4.0    0.95
Conteúdo gratuito oferecido pelo produtor            4.1     4.0    0.83
Garantia de devolução do dinheiro                    2.0     2.0     0.0
Preço                                                3.3     3.0    0.48
Qualidade da apresentação (vídeo, áudio, design...   4.1     4.0    0.87
Recomendações de amigos/familiares                   3.6     4.0     1.1

------------------------------

Percepção da Experiência com o Produto             Média Mediana DesvPad
Influência na Compra
Avaliações e depoimentos de clientes                 4.2     4.0    0.64
Conteúdo do infoproduto (tema/relevância)            4.1     4.0    0.76
Conteúdo gratuito oferecido pelo produtor            3.9     4.0    0.83
Garantia de devolução do dinheiro                    3.5     3.5     2.1
Preço                                                3.5     4.0    0.52
Qualidade da apresentação (vídeo, áudio, design...   4.2     4.0    0.78
Recomendações de amigos/familiares                   3.7     4.0     1.1

------------------------------

Indicaria o Produto                                Média Mediana DesvPad
Influência na Compra
Avaliações e depoimentos de clientes                 4.3     4.0    0.72
Conteúdo do infoproduto (tema/relevância)            4.1     4.0    0.86
Conteúdo gratuito oferecido pelo produtor            4.0     4.0     1.0
Garantia de devolução do dinheiro                    3.5     3.5     2.1
Preço                                                3.3     3.0     1.0
Qualidade da apresentação (vídeo, áudio, design...   4.1     4.0    0.76
Recomendações de amigos/familiares                   3.8     4.0     1.1

------------------------------

Frequência no Consumo                              Média Mediana DesvPad
Primeiro Contato
Pesquisa em mecanismos de busca, como o Google       3.5     4.0     1.3
Por meio das redes sociais, como Instagram, Tik...   3.5     3.5     1.2
Por meio de anúncios online, como no Facebook o...   3.1     3.0     1.4
Recomendação de amigos ou colegas                    3.0     3.0     1.3

------------------------------

Benefícios da Mentoria                             Média Mediana DesvPad
Primeiro Contato
Pesquisa em mecanismos de busca, como o Google       3.9     4.0    0.91
Por meio das redes sociais, como Instagram, Tik...   4.0     4.0    0.99
Por meio de anúncios online, como no Facebook o...   4.0     4.0    0.88
Recomendação de amigos ou colegas                    4.1     4.0    0.93

------------------------------

Meta Melhora o Progresso                           Média Mediana DesvPad
Primeiro Contato
Pesquisa em mecanismos de busca, como o Google       4.1     4.0    0.73
Por meio das redes sociais, como Instagram, Tik...   4.2     4.0    0.97
Por meio de anúncios online, como no Facebook o...   3.4     3.0    0.93
Recomendação de amigos ou colegas                    4.3     4.5    0.75

------------------------------

Variedade Melhora a Experiência                    Média Mediana DesvPad
Primeiro Contato
Pesquisa em mecanismos de busca, como o Google       4.7     5.0    0.53
Por meio das redes sociais, como Instagram, Tik...   4.5     5.0    0.84
Por meio de anúncios online, como no Facebook o...   4.4     5.0    0.84
Recomendação de amigos ou colegas                    4.3     4.5    0.78

------------------------------

Satisfação com o Produto                           Média Mediana DesvPad
Primeiro Contato
Pesquisa em mecanismos de busca, como o Google       3.9     4.0    0.97
Por meio das redes sociais, como Instagram, Tik...   3.9     4.0    0.99
Por meio de anúncios online, como no Facebook o...   3.9     4.0     1.0
Recomendação de amigos ou colegas                    3.9     4.0    0.83

------------------------------

Percepção da Experiência com o Produto             Média Mediana DesvPad
Primeiro Contato
Pesquisa em mecanismos de busca, como o Google       3.9     4.0    0.78
Por meio das redes sociais, como Instagram, Tik...   4.0     4.0    0.82
Por meio de anúncios online, como no Facebook o...   3.9     4.0    0.92
Recomendação de amigos ou colegas                    3.9     4.0    0.86

------------------------------

Indicaria o Produto                                Média Mediana DesvPad
Primeiro Contato
Pesquisa em mecanismos de busca, como o Google       3.9     4.0    0.74
Por meio das redes sociais, como Instagram, Tik...   4.1     4.0     1.0
Por meio de anúncios online, como no Facebook o...   4.1     4.0    0.95
Recomendação de amigos ou colegas                    3.9     4.0    0.95

------------------------------

Frequência no Consumo                              Média Mediana DesvPad
Motivação para Compra
Aquisição de conhecimento específico                 3.5     4.0     1.2
Desenvolvimento de habilidades técnicas              3.7     4.0     1.2
Empreendedorismo ou criação de negócio próprio       3.0     3.0     nan
Facilidade de aprendizado online                     3.1     3.0     1.1
Flexibilidade de horário de estudo                   3.1     3.0    0.99
Ganhos financeiros                                   2.4     2.0     1.2
Indicação de colegas ou amigos                       2.5     2.0     1.9
Mudar de Carreira (aprender uma nova profissão)      3.3     3.5     1.6
Preparação para exames, concursos ou certificações   3.5     4.0     1.3
Realização de objetivos de vida                      3.2     3.0     1.7
Solução para um problema específico                  3.0     2.0     1.7

------------------------------

Benefícios da Mentoria                             Média Mediana DesvPad
Motivação para Compra
Aquisição de conhecimento específico                 4.0     4.0     1.0
Desenvolvimento de habilidades técnicas              4.3     5.0    0.82
Empreendedorismo ou criação de negócio próprio       3.0     3.0     nan
Facilidade de aprendizado online                     3.3     3.0     1.1
Flexibilidade de horário de estudo                   4.3     4.0     0.8
Ganhos financeiros                                   4.6     5.0    0.88
Indicação de colegas ou amigos                       4.0     4.0    0.82
Mudar de Carreira (aprender uma nova profissão)      4.1     4.0     0.9
Preparação para exames, concursos ou certificações   4.0     4.0    0.68
Realização de objetivos de vida                      3.8     4.0    0.98
Solução para um problema específico                  3.3     3.0     1.5

------------------------------

Meta Melhora o Progresso                           Média Mediana DesvPad
Motivação para Compra
Aquisição de conhecimento específico                 4.1     4.0    0.77
Desenvolvimento de habilidades técnicas              4.5     5.0    0.64
Empreendedorismo ou criação de negócio próprio       3.0     3.0     nan
Facilidade de aprendizado online                     4.1     4.0     0.7
Flexibilidade de horário de estudo                   4.4     5.0    0.74
Ganhos financeiros                                   4.0     5.0     1.4
Indicação de colegas ou amigos                       3.8     4.5     1.9
Mudar de Carreira (aprender uma nova profissão)      4.2     4.5    0.87
Preparação para exames, concursos ou certificações   4.1     4.0    0.86
Realização de objetivos de vida                      4.3     5.0     1.0
Solução para um problema específico                  3.7     4.0     1.5

------------------------------

Variedade Melhora a Experiência                    Média Mediana DesvPad
Motivação para Compra
Aquisição de conhecimento específico                 4.5     5.0    0.73
Desenvolvimento de habilidades técnicas              4.7     5.0    0.62
Empreendedorismo ou criação de negócio próprio       3.0     3.0     nan
Facilidade de aprendizado online                     4.7     5.0    0.65
Flexibilidade de horário de estudo                   4.5     5.0    0.83
Ganhos financeiros                                   4.7     5.0    0.71
Indicação de colegas ou amigos                       3.8     3.5    0.96
Mudar de Carreira (aprender uma nova profissão)      4.2     4.5    0.87
Preparação para exames, concursos ou certificações   4.4     5.0    0.82
Realização de objetivos de vida                      4.4     5.0    0.81
Solução para um problema específico                  4.0     4.0     1.0

------------------------------

Satisfação com o Produto                           Média Mediana DesvPad
Motivação para Compra
Aquisição de conhecimento específico                 3.9     4.0    0.84
Desenvolvimento de habilidades técnicas              3.9     4.0    0.96
Empreendedorismo ou criação de negócio próprio       3.0     3.0     nan
Facilidade de aprendizado online                     3.9     4.0     0.7
Flexibilidade de horário de estudo                   3.9     4.0    0.64
Ganhos financeiros                                   3.8     3.0     1.2
Indicação de colegas ou amigos                       3.0     3.5     1.4
Mudar de Carreira (aprender uma nova profissão)      4.0     4.5     1.1
Preparação para exames, concursos ou certificações   4.0     4.0    0.98
Realização de objetivos de vida                      4.2     5.0    0.98
Solução para um problema específico                  3.3     3.0     1.5

------------------------------

Percepção da Experiência com o Produto             Média Mediana DesvPad
Motivação para Compra
Aquisição de conhecimento específico                 3.9     4.0    0.66
Desenvolvimento de habilidades técnicas              3.9     4.0    0.92
Empreendedorismo ou criação de negócio próprio       3.0     3.0     nan
Facilidade de aprendizado online                     4.1     4.0     0.7
Flexibilidade de horário de estudo                   4.0     4.0    0.53
Ganhos financeiros                                   3.9     4.0     1.1
Indicação de colegas ou amigos                       3.2     3.5    0.96
Mudar de Carreira (aprender uma nova profissão)      4.2     4.5     1.0
Preparação para exames, concursos ou certificações   4.1     4.0    0.93
Realização de objetivos de vida                      4.1     4.0    0.94
Solução para um problema específico                  3.7     4.0     1.5

------------------------------

Indicaria o Produto                                Média Mediana DesvPad
Motivação para Compra
Aquisição de conhecimento específico                 4.1     4.0    0.72
Desenvolvimento de habilidades técnicas              3.9     4.0     1.1
Empreendedorismo ou criação de negócio próprio       4.0     4.0     nan
Facilidade de aprendizado online                     4.0     4.0    0.63
Flexibilidade de horário de estudo                   4.0     4.0    0.85
Ganhos financeiros                                   3.9     4.0     1.2
Indicação de colegas ou amigos                       3.5     3.5    0.58
Mudar de Carreira (aprender uma nova profissão)      3.7     4.0     1.3
Preparação para exames, concursos ou certificações   4.1     4.0     1.0
Realização de objetivos de vida                      4.4     5.0    0.81
Solução para um problema específico                  3.0     3.0     2.0

------------------------------